// <auto-generated />
using Assessment_BernersLee_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assessment_BernersLee_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241115181751_SeedPatients")]
    partial class SeedPatients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Assessment_BernersLee_API.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "erwin.smith@example.com",
                            LastName = "smith",
                            Name = "erwin",
                            Password = "password123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "majopino@example.com",
                            LastName = "pino",
                            Name = "majo",
                            Password = "password456"
                        },
                        new
                        {
                            Id = 3,
                            Email = "admin@example.com",
                            LastName = "admin",
                            Name = "admin",
                            Password = "admin123"
                        });
                });

            modelBuilder.Entity("Assessment_BernersLee_API.Models.Medic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("medics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            IdentificationNumber = "1234567890",
                            LastName = "Doe",
                            Name = "John",
                            Password = "password123",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "alice.johnson@example.com",
                            IdentificationNumber = "9876543210",
                            LastName = "Johnson",
                            Name = "Alice",
                            Password = "password456",
                            PhoneNumber = "2345678901"
                        },
                        new
                        {
                            Id = 3,
                            Email = "michael.williams@example.com",
                            IdentificationNumber = "1122334455",
                            LastName = "Williams",
                            Name = "Michael",
                            Password = "password789",
                            PhoneNumber = "3456789012"
                        },
                        new
                        {
                            Id = 4,
                            Email = "sarah.brown@example.com",
                            IdentificationNumber = "2233445566",
                            LastName = "Brown",
                            Name = "Sarah",
                            Password = "password321",
                            PhoneNumber = "4567890123"
                        },
                        new
                        {
                            Id = 5,
                            Email = "david.davis@example.com",
                            IdentificationNumber = "3344556677",
                            LastName = "Davis",
                            Name = "David",
                            Password = "password654",
                            PhoneNumber = "5678901234"
                        },
                        new
                        {
                            Id = 6,
                            Email = "emily.miller@example.com",
                            IdentificationNumber = "4455667788",
                            LastName = "Miller",
                            Name = "Emily",
                            Password = "password987",
                            PhoneNumber = "6789012345"
                        },
                        new
                        {
                            Id = 7,
                            Email = "james.wilson@example.com",
                            IdentificationNumber = "5566778899",
                            LastName = "Wilson",
                            Name = "James",
                            Password = "password1234",
                            PhoneNumber = "7890123456"
                        },
                        new
                        {
                            Id = 8,
                            Email = "jessica.moore@example.com",
                            IdentificationNumber = "6677889900",
                            LastName = "Moore",
                            Name = "Jessica",
                            Password = "password4321",
                            PhoneNumber = "8901234567"
                        },
                        new
                        {
                            Id = 9,
                            Email = "daniel.taylor@example.com",
                            IdentificationNumber = "7788990011",
                            LastName = "Taylor",
                            Name = "Daniel",
                            Password = "password567",
                            PhoneNumber = "9012345678"
                        },
                        new
                        {
                            Id = 10,
                            Email = "olivia.anderson@example.com",
                            IdentificationNumber = "8899001122",
                            LastName = "Anderson",
                            Name = "Olivia",
                            Password = "password876",
                            PhoneNumber = "1234567899"
                        },
                        new
                        {
                            Id = 11,
                            Email = "matthew.thomas@example.com",
                            IdentificationNumber = "9900112233",
                            LastName = "Thomas",
                            Name = "Matthew",
                            Password = "password2345",
                            PhoneNumber = "2345678908"
                        },
                        new
                        {
                            Id = 12,
                            Email = "sophia.jackson@example.com",
                            IdentificationNumber = "1001122334",
                            LastName = "Jackson",
                            Name = "Sophia",
                            Password = "password5678",
                            PhoneNumber = "3456789017"
                        },
                        new
                        {
                            Id = 13,
                            Email = "ethan.white@example.com",
                            IdentificationNumber = "1112233445",
                            LastName = "White",
                            Name = "Ethan",
                            Password = "password8901",
                            PhoneNumber = "4567890126"
                        },
                        new
                        {
                            Id = 14,
                            Email = "charlotte.harris@example.com",
                            IdentificationNumber = "2223344556",
                            LastName = "Harris",
                            Name = "Charlotte",
                            Password = "password12345",
                            PhoneNumber = "5678901235"
                        },
                        new
                        {
                            Id = 15,
                            Email = "benjamin.martin@example.com",
                            IdentificationNumber = "3334455667",
                            LastName = "Martin",
                            Name = "Benjamin",
                            Password = "password6789",
                            PhoneNumber = "6789012346"
                        },
                        new
                        {
                            Id = 16,
                            Email = "avery.lee@example.com",
                            IdentificationNumber = "4445566778",
                            LastName = "Lee",
                            Name = "Avery",
                            Password = "password234",
                            PhoneNumber = "7890123457"
                        },
                        new
                        {
                            Id = 17,
                            Email = "mason.perez@example.com",
                            IdentificationNumber = "5556677889",
                            LastName = "Perez",
                            Name = "Mason",
                            Password = "password8765",
                            PhoneNumber = "8901234568"
                        },
                        new
                        {
                            Id = 18,
                            Email = "lily.wilson@example.com",
                            IdentificationNumber = "6667788990",
                            LastName = "Wilson",
                            Name = "Lily",
                            Password = "password5432",
                            PhoneNumber = "9012345679"
                        },
                        new
                        {
                            Id = 19,
                            Email = "henry.gonzalez@example.com",
                            IdentificationNumber = "7778899001",
                            LastName = "Gonzalez",
                            Name = "Henry",
                            Password = "password9876",
                            PhoneNumber = "1234567800"
                        },
                        new
                        {
                            Id = 20,
                            Email = "zoe.rodriguez@example.com",
                            IdentificationNumber = "8889900112",
                            LastName = "Rodriguez",
                            Name = "Zoe",
                            Password = "password432",
                            PhoneNumber = "2345678910"
                        });
                });

            modelBuilder.Entity("Assessment_BernersLee_API.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("PatientDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("patient_description");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jane.smith@example.com",
                            IdentificationNumber = "9876543210",
                            LastName = "Smith",
                            Name = "Jane",
                            Password = "password123",
                            PatientDescription = "Jane is a 35-year-old woman with a history of heart disease.",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            Id = 2,
                            Email = "oliver.brown@example.com",
                            IdentificationNumber = "1234567890",
                            LastName = "Brown",
                            Name = "Oliver",
                            Password = "password456",
                            PatientDescription = "Oliver is a 42-year-old man recovering from a recent knee surgery.",
                            PhoneNumber = "1234567890"
                        },
                        new
                        {
                            Id = 3,
                            Email = "emily.davis@example.com",
                            IdentificationNumber = "1122334455",
                            LastName = "Davis",
                            Name = "Emily",
                            Password = "password789",
                            PatientDescription = "Emily is a 29-year-old woman undergoing treatment for asthma.",
                            PhoneNumber = "2345678901"
                        },
                        new
                        {
                            Id = 4,
                            Email = "james.wilson@example.com",
                            IdentificationNumber = "2233445566",
                            LastName = "Wilson",
                            Name = "James",
                            Password = "password321",
                            PatientDescription = "James is a 60-year-old man with diabetes and high blood pressure.",
                            PhoneNumber = "3456789012"
                        },
                        new
                        {
                            Id = 5,
                            Email = "sophia.martinez@example.com",
                            IdentificationNumber = "3344556677",
                            LastName = "Martinez",
                            Name = "Sophia",
                            Password = "password654",
                            PatientDescription = "Sophia is a 50-year-old woman being treated for chronic migraines.",
                            PhoneNumber = "4567890123"
                        },
                        new
                        {
                            Id = 6,
                            Email = "benjamin.garcia@example.com",
                            IdentificationNumber = "4455667788",
                            LastName = "Garcia",
                            Name = "Benjamin",
                            Password = "password987",
                            PatientDescription = "Benjamin is a 38-year-old man with a recent diagnosis of depression.",
                            PhoneNumber = "5678901234"
                        },
                        new
                        {
                            Id = 7,
                            Email = "mia.lopez@example.com",
                            IdentificationNumber = "5566778899",
                            LastName = "Lopez",
                            Name = "Mia",
                            Password = "password1234",
                            PatientDescription = "Mia is a 27-year-old woman with a history of seasonal allergies.",
                            PhoneNumber = "6789012345"
                        },
                        new
                        {
                            Id = 8,
                            Email = "ethan.hernandez@example.com",
                            IdentificationNumber = "6677889900",
                            LastName = "Hernandez",
                            Name = "Ethan",
                            Password = "password4321",
                            PatientDescription = "Ethan is a 45-year-old man recovering from a stroke.",
                            PhoneNumber = "7890123456"
                        },
                        new
                        {
                            Id = 9,
                            Email = "charlotte.gonzalez@example.com",
                            IdentificationNumber = "7788990011",
                            LastName = "Gonzalez",
                            Name = "Charlotte",
                            Password = "password567",
                            PatientDescription = "Charlotte is a 32-year-old woman with autoimmune disorder treatment.",
                            PhoneNumber = "8901234567"
                        },
                        new
                        {
                            Id = 10,
                            Email = "liam.rodriguez@example.com",
                            IdentificationNumber = "8899001122",
                            LastName = "Rodriguez",
                            Name = "Liam",
                            Password = "password876",
                            PatientDescription = "Liam is a 40-year-old man recovering from a sports injury.",
                            PhoneNumber = "9012345678"
                        },
                        new
                        {
                            Id = 11,
                            Email = "isabella.perez@example.com",
                            IdentificationNumber = "9900112233",
                            LastName = "Perez",
                            Name = "Isabella",
                            Password = "password2345",
                            PatientDescription = "Isabella is a 24-year-old woman undergoing physical therapy.",
                            PhoneNumber = "1234567899"
                        },
                        new
                        {
                            Id = 12,
                            Email = "lucas.hall@example.com",
                            IdentificationNumber = "1001122334",
                            LastName = "Hall",
                            Name = "Lucas",
                            Password = "password5678",
                            PatientDescription = "Lucas is a 55-year-old man with chronic back pain.",
                            PhoneNumber = "2345678908"
                        },
                        new
                        {
                            Id = 13,
                            Email = "ava.allen@example.com",
                            IdentificationNumber = "1112233445",
                            LastName = "Allen",
                            Name = "Ava",
                            Password = "password8901",
                            PatientDescription = "Ava is a 19-year-old woman with a history of anemia.",
                            PhoneNumber = "3456789017"
                        },
                        new
                        {
                            Id = 14,
                            Email = "noah.young@example.com",
                            IdentificationNumber = "2223344556",
                            LastName = "Young",
                            Name = "Noah",
                            Password = "password12345",
                            PatientDescription = "Noah is a 36-year-old man with high cholesterol.",
                            PhoneNumber = "4567890126"
                        },
                        new
                        {
                            Id = 15,
                            Email = "grace.king@example.com",
                            IdentificationNumber = "3334455667",
                            LastName = "King",
                            Name = "Grace",
                            Password = "password6789",
                            PatientDescription = "Grace is a 48-year-old woman being treated for arthritis.",
                            PhoneNumber = "5678901235"
                        },
                        new
                        {
                            Id = 16,
                            Email = "logan.wright@example.com",
                            IdentificationNumber = "4445566778",
                            LastName = "Wright",
                            Name = "Logan",
                            Password = "password234",
                            PatientDescription = "Logan is a 30-year-old man recovering from appendicitis surgery.",
                            PhoneNumber = "6789012346"
                        },
                        new
                        {
                            Id = 17,
                            Email = "ella.scott@example.com",
                            IdentificationNumber = "5556677889",
                            LastName = "Scott",
                            Name = "Ella",
                            Password = "password8765",
                            PatientDescription = "Ella is a 22-year-old woman with celiac disease.",
                            PhoneNumber = "7890123457"
                        },
                        new
                        {
                            Id = 18,
                            Email = "jacob.torres@example.com",
                            IdentificationNumber = "6667788990",
                            LastName = "Torres",
                            Name = "Jacob",
                            Password = "password5432",
                            PatientDescription = "Jacob is a 59-year-old man undergoing cancer treatment.",
                            PhoneNumber = "8901234568"
                        },
                        new
                        {
                            Id = 19,
                            Email = "victoria.nguyen@example.com",
                            IdentificationNumber = "7778899001",
                            LastName = "Nguyen",
                            Name = "Victoria",
                            Password = "password9876",
                            PatientDescription = "Victoria is a 62-year-old woman with hypertension.",
                            PhoneNumber = "9012345679"
                        },
                        new
                        {
                            Id = 20,
                            Email = "henry.lewis@example.com",
                            IdentificationNumber = "8889900112",
                            LastName = "Lewis",
                            Name = "Henry",
                            Password = "password432",
                            PatientDescription = "Henry is a 43-year-old man with thyroid issues.",
                            PhoneNumber = "1234567800"
                        },
                        new
                        {
                            Id = 21,
                            Email = "luna.walker@example.com",
                            IdentificationNumber = "9990011223",
                            LastName = "Walker",
                            Name = "Luna",
                            Password = "password6543",
                            PatientDescription = "Luna is a 29-year-old woman with chronic fatigue.",
                            PhoneNumber = "2345678910"
                        },
                        new
                        {
                            Id = 22,
                            Email = "jack.hill@example.com",
                            IdentificationNumber = "1011122334",
                            LastName = "Hill",
                            Name = "Jack",
                            Password = "password87654",
                            PatientDescription = "Jack is a 51-year-old man recovering from hip replacement surgery.",
                            PhoneNumber = "3456789021"
                        },
                        new
                        {
                            Id = 23,
                            Email = "chloe.green@example.com",
                            IdentificationNumber = "1112233445",
                            LastName = "Green",
                            Name = "Chloe",
                            Password = "password123456",
                            PatientDescription = "Chloe is a 37-year-old woman managing chronic sinus infections.",
                            PhoneNumber = "4567890132"
                        },
                        new
                        {
                            Id = 24,
                            Email = "samuel.adams@example.com",
                            IdentificationNumber = "2223344556",
                            LastName = "Adams",
                            Name = "Samuel",
                            Password = "password78901",
                            PatientDescription = "Samuel is a 47-year-old man with kidney stones.",
                            PhoneNumber = "5678901243"
                        },
                        new
                        {
                            Id = 25,
                            Email = "zoe.carter@example.com",
                            IdentificationNumber = "3334455667",
                            LastName = "Carter",
                            Name = "Zoe",
                            Password = "password54321",
                            PatientDescription = "Zoe is a 26-year-old woman undergoing psychological therapy.",
                            PhoneNumber = "6789012354"
                        },
                        new
                        {
                            Id = 26,
                            Email = "nathan.baker@example.com",
                            IdentificationNumber = "4445566778",
                            LastName = "Baker",
                            Name = "Nathan",
                            Password = "password67890",
                            PatientDescription = "Nathan is a 39-year-old man recovering from a motorcycle accident.",
                            PhoneNumber = "7890123465"
                        },
                        new
                        {
                            Id = 27,
                            Email = "stella.nelson@example.com",
                            IdentificationNumber = "5556677889",
                            LastName = "Nelson",
                            Name = "Stella",
                            Password = "password234567",
                            PatientDescription = "Stella is a 33-year-old woman with epilepsy.",
                            PhoneNumber = "8901234576"
                        },
                        new
                        {
                            Id = 28,
                            Email = "elias.mitchell@example.com",
                            IdentificationNumber = "6667788990",
                            LastName = "Mitchell",
                            Name = "Elias",
                            Password = "password76543",
                            PatientDescription = "Elias is a 41-year-old man with a history of chronic headaches.",
                            PhoneNumber = "9012345687"
                        },
                        new
                        {
                            Id = 29,
                            Email = "hannah.rivera@example.com",
                            IdentificationNumber = "7778899001",
                            LastName = "Rivera",
                            Name = "Hannah",
                            Password = "password45678",
                            PatientDescription = "Hannah is a 34-year-old woman with a persistent rash.",
                            PhoneNumber = "1234567898"
                        },
                        new
                        {
                            Id = 30,
                            Email = "ryan.parker@example.com",
                            IdentificationNumber = "8889900112",
                            LastName = "Parker",
                            Name = "Ryan",
                            Password = "password876543",
                            PatientDescription = "Ryan is a 25-year-old man recovering from a sports-related injury.",
                            PhoneNumber = "2345678909"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
